"""Public contract surface: ``from twin_common.contracts import ModelOutput`` and friends.

docs/02 section 4 is the specification; :mod:`twin_common.contracts.models` is the
implementation. Nothing outside this package may define another response shape.
"""

from __future__ import annotations

from .enums import (
    REASON_REQUIRED_LEVELS,
    RESOURCE_TYPES,
    DataSource,
    Engine,
    EntityType,
    RiskLevel,
    State,
    Status,
    UpstreamSource,
)
from .export import SCHEMA_TARGETS, export_schemas, schema_for
from .ids import (
    ENTITY_ID_PATTERNS,
    EVENT_ID,
    KPI_NAME_RE,
    MODEL_ID_RE,
    REASON_CODE_RE,
    SCENARIO_ID_RE,
    SEMVER_RE,
    infer_entity_types,
    is_valid_entity_id,
    is_valid_model_id,
    is_valid_scenario_id,
    validate_entity_id,
)
from .models import (
    IST,
    SCHEMA_VERSION,
    ErrorResponse,
    HealthResponse,
    KpiDescriptor,
    Metadata,
    ModelOutput,
    PredictRequest,
    Recommendation,
    ResultRecord,
    ScenarioRequest,
    UpstreamRef,
    new_run_id,
    now_ist,
    to_ist,
)
from .registry import (
    KpiInfo,
    ModelInfo,
    all_bands,
    all_kpis,
    all_models,
    all_reason_codes,
    all_resource_types,
    allowed_units,
    band_table,
    downstream_of,
    kpi_exists,
    kpi_info,
    kpi_unit,
    kpis_owned_by,
    model_exists,
    model_info,
    resource_available,
    resource_type_exists,
    topological_order,
    upstream_of,
)

__all__ = [
    # ids
    "ENTITY_ID_PATTERNS",
    "EVENT_ID",
    # models
    "IST",
    "KPI_NAME_RE",
    "MODEL_ID_RE",
    "REASON_CODE_RE",
    "REASON_REQUIRED_LEVELS",
    "RESOURCE_TYPES",
    "SCENARIO_ID_RE",
    # schema export
    "SCHEMA_TARGETS",
    "SCHEMA_VERSION",
    "SEMVER_RE",
    # enums
    "DataSource",
    "Engine",
    "EntityType",
    "ErrorResponse",
    "HealthResponse",
    "KpiDescriptor",
    # registry
    "KpiInfo",
    "Metadata",
    "ModelInfo",
    "ModelOutput",
    "PredictRequest",
    "Recommendation",
    "ResultRecord",
    "RiskLevel",
    "ScenarioRequest",
    "State",
    "Status",
    "UpstreamRef",
    "UpstreamSource",
    "all_bands",
    "all_kpis",
    "all_models",
    "all_reason_codes",
    "all_resource_types",
    "allowed_units",
    "band_table",
    "downstream_of",
    "export_schemas",
    "infer_entity_types",
    "is_valid_entity_id",
    "is_valid_model_id",
    "is_valid_scenario_id",
    "kpi_exists",
    "kpi_info",
    "kpi_unit",
    "kpis_owned_by",
    "model_exists",
    "model_info",
    "new_run_id",
    "now_ist",
    "resource_available",
    "resource_type_exists",
    "schema_for",
    "to_ist",
    "topological_order",
    "upstream_of",
    "validate_entity_id",
]
